### ISSUE TITLE
Game broken

### ISSUE THREAD

**Issue by bellstar** [ghdevelopers2410a/github-games-t6da#1]
When attempting to access this at https://ghdevelopers2410a.github.io/github-games-t6da, I am getting a 404. This could be caused by a couple of things:

- GitHub Pages needs to be enabled on the  branch. You can fix this in the repository settings.
- The **index.html** file is incorrectly named **inde.html**. We will fix this together in class.

Can you fix the first bullet, please?

**Comment by t6da** [comment]
https://github.com/ghdevelopers2410a/github-games-t6da/pull/4
こちらで解消したのでクローズ
